const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const PDFDocument = require("pdfkit");

const Certificate = require("../models/Certificate");
const Enrollment = require("../models/Enrollment");
const Course = require("../models/Course");
const User = require("../models/User");

const ensureDir = (dir) => {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
};

const formatDate = (d) => {
  const dt = new Date(d);
  if (Number.isNaN(dt.getTime())) return "";
  return dt.toISOString().slice(0, 10);
};

const buildCertificateNo = () => {
  const stamp = Date.now().toString(36).toUpperCase();
  const rand = crypto.randomBytes(4).toString("hex").toUpperCase();
  return `CERT-${stamp}-${rand}`;
};

const generateCertificatePdf = async ({ filePath, studentName, courseTitle, certificateNo, issuedAt }) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margin: 50,
      });

      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      // Background style (simple)
      doc.rect(20, 20, doc.page.width - 40, doc.page.height - 40).lineWidth(2).stroke();

      doc
        .fontSize(28)
        .text("Certificate of Completion", { align: "center" })
        .moveDown(1);

      doc.fontSize(14).text("This certifies that", { align: "center" }).moveDown(0.6);

      doc.fontSize(24).text(studentName, { align: "center" }).moveDown(0.6);

      doc.fontSize(14).text("has successfully completed the course", { align: "center" }).moveDown(0.6);

      doc.fontSize(20).text(courseTitle, { align: "center" }).moveDown(1.2);

      doc.fontSize(12).text(`Certificate No: ${certificateNo}`, { align: "center" });
      doc.fontSize(12).text(`Issued At: ${formatDate(issuedAt)}`, { align: "center" });

      // Signature area
      doc.moveDown(3);
      const y = doc.y;
      doc
        .moveTo(120, y)
        .lineTo(260, y)
        .stroke();
      doc
        .moveTo(335, y)
        .lineTo(475, y)
        .stroke();

      doc.moveDown(0.3);
      doc.fontSize(11).text("Platform Admin", 120, y + 10, { width: 140, align: "center" });
      doc.fontSize(11).text("Instructor", 335, y + 10, { width: 140, align: "center" });

      // Footer
      doc.fontSize(9).text("Generated by LMS System", 0, doc.page.height - 60, { align: "center" });

      doc.end();

      stream.on("finish", () => resolve(true));
      stream.on("error", reject);
    } catch (err) {
      reject(err);
    }
  });
};

// -----------------------------------------
// POST /courses/:id/certificate/generate
// شرط: enrollment باید 100% یا isCompleted=true باشد
// -----------------------------------------
const generateCertificate = async (req, res, next) => {
  try {
    const courseId = req.params.id;
    const studentId = req.user.userId;

    const enrollment = await Enrollment.findOne({ courseId, studentId }).select(
      "progressPercent isCompleted completedAt"
    );

    if (!enrollment) {
      return res.status(400).json({ message: "You are not enrolled in this course" });
    }

    const completedOk = enrollment.isCompleted === true || Number(enrollment.progressPercent) >= 100;
    if (!completedOk) {
      return res.status(400).json({
        message: "Course is not completed yet. Complete 100% to generate certificate.",
        progressPercent: enrollment.progressPercent,
      });
    }

    // اگر قبلاً ساخته شده باشد
    const existing = await Certificate.findOne({ courseId, studentId })
      .populate("courseId", "title")
      .sort({ createdAt: -1 });

    if (existing && existing.pdfUrl) {
      return res.status(200).json({
        message: "Certificate already generated",
        certificate: existing,
      });
    }

    const [course, student] = await Promise.all([
      Course.findById(courseId).select("title status"),
      User.findById(studentId).select("name email"),
    ]);

    if (!course) return res.status(404).json({ message: "Course not found" });
    if (!student) return res.status(404).json({ message: "Student not found" });

    // مسیر ذخیره فایل
    const baseUploads = path.join(__dirname, "..", "uploads", "certificates");
    ensureDir(baseUploads);

    const certificateNo = buildCertificateNo();
    const fileName = `${certificateNo}.pdf`;
    const filePath = path.join(baseUploads, fileName);

    const issuedAt = new Date();

    await generateCertificatePdf({
      filePath,
      studentName: student.name || student.email,
      courseTitle: course.title,
      certificateNo,
      issuedAt,
    });

    // url دانلود (از روی host فعلی)
    const pdfUrl = `${req.protocol}://${req.get("host")}/uploads/certificates/${fileName}`;

    const certificate = await Certificate.create({
      courseId,
      studentId,
      certificateNo,
      issuedAt,
      pdfUrl,
      progressSnapshot: {
        progressPercent: enrollment.progressPercent,
        completedAt: enrollment.completedAt || issuedAt,
      },
    });

    return res.status(201).json({
      message: "Certificate generated",
      certificate,
    });
  } catch (err) {
    // duplicate unique index (race)
    if (err && err.code === 11000) {
      const cert = await Certificate.findOne({
        courseId: req.params.id,
        studentId: req.user.userId,
      });
      return res.status(200).json({ message: "Certificate already generated", certificate: cert });
    }
    next(err);
  }
};

// -----------------------------------------
// GET /me/certificates
// -----------------------------------------
const getMyCertificates = async (req, res, next) => {
  try {
    const studentId = req.user.userId;

    const certificates = await Certificate.find({ studentId })
      .populate("courseId", "title")
      .sort({ issuedAt: -1 });

    return res.status(200).json({ certificates });
  } catch (err) {
    next(err);
  }
};

module.exports = {
  generateCertificate,
  getMyCertificates,
};
